# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'egel/tmux-gruvbox'
set -g @plugin 'sei40kr/tmux-onedark'

bind C-l send-keys 'C-l' # clear screen

bind -n M-down resize-pane -D 5
bind -n M-up resize-pane -U 5
bind -n M-left resize-pane -L 5
bind -n M-right resize-pane -R 5

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
