# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'carlocab/tmux-nvr'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'arcticicestudio/nord-tmux'
# set -g @plugin 'dracula/tmux'

set -g @dracula-show-left-icon session
set -g @dracula-show-battery false
set -g @dracula-show-location false
set -g @dracula-show-network false
set -g @dracula-show-time false
set -g @dracula-show-weather false
set -g @nord_tmux_no_patched_font '1'

# set -g default-terminal "screen-256color-italic"
# set-option -ga terminal-overrides ",xterm-256color*:Tc:smso"

set -g default-terminal 'tmux-256color'
# set -as terminal-overrides ',xterm*:Tc:sitm=\E[3m'

# Undercurl
# set -g default-terminal "${TERM}"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0

# copy selections using `y`
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel
# toggle the status bar
bind-key s set-option status
# reload this config file
bind r source-file ~/.tmux.conf \; display "Fresh Tmux Config!"

bind C-l send-keys 'C-l' # clear screen

bind -n M-down resize-pane -D 5
bind -n M-up resize-pane -U 5
bind -n M-left resize-pane -L 5
bind -n M-right resize-pane -R 5

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
