format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$nix_shell\
$character"""

[directory]
style = "blue"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = " $branch"

[git_status]
untracked = '[ $count]() '
deleted = '[-$count]() '
modified = '[±$count]() '
staged = '[+$count]() '
renamed = '[ $count]() '
behind = '[ ]() '
ahead = '[ ]() '
diverged = '[נּ]($style)'
format = "[ [($conflicted$untracked$modified$deleted$staged$renamed)](218) ($ahead_behind)]($style)"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"

[nix_shell]
format = "[$symbol $name]($style) "
heuristic = true
symbol = " "
