-- [nfnl] Compiled from fnl/own/window-mappings.fnl by https://github.com/Olical/nfnl, do not edit.
vim.keymap.set("n", "<M-,>", "<C-W>5<")
vim.keymap.set("n", "<M-.>", "<C-W>5>")
vim.keymap.set("n", "<M-->", "<C-W>5-")
vim.keymap.set("n", "<M-=>", "<C-W>5+")
vim.keymap.set("t", "<M-,>", "<C-\\><C-n><C-W>5<")
vim.keymap.set("t", "<M-.>", "<C-\\><C-n><C-W>5>")
vim.keymap.set("t", "<M-->", "<C-\\><C-n><C-W>5-")
vim.keymap.set("t", "<M-=>", "<C-\\><C-n><C-W>5+")
vim.keymap.set("t", "<M-k>", "<C-\\><C-n><C-W>k")
vim.keymap.set("t", "<M-j>", "<C-\\><C-n><C-W>j")
vim.keymap.set("t", "<M-h>", "<C-\\><C-n><C-W>h")
vim.keymap.set("t", "<M-l>", "<C-\\><C-n><C-W>l")
vim.keymap.set("n", "<leader>wz", "<cmd>tabnew %<cr>", {desc = "zoom window"})
local group = vim.api.nvim_create_augroup("auto-resize-windows", {clear = true})
vim.api.nvim_create_autocmd("VimResized", {pattern = "*", command = "wincmd =", group = group})
return nil
