#!/usr/bin/env bash

sketchybar -m --bar blur_radius=50                                                            \
              --add item apple.logo left                                                      \
              --set apple.logo icon=                                                         \
                               icon.font="$FONT_FACE:Regular:15.0"                            \
                               label.drawing=on                                               \
                               icon.padding_right=0                                           \
                               background.padding_right=5                                     \
                               click_script="sketchybar -m --set \$NAME popup.drawing=toggle" \
                               popup.background.border_width=2                                \
                               popup.background.corner_radius=3                               \
                               popup.background.border_color=0xffffffff                       \
                               popup.background.color=0xff24273a                              \
                                                                                              \
              --add item apple.preferences popup.apple.logo                                   \
              --set apple.preferences icon=􀺽                                                  \
                               label="Preferences"                                            \
                               click_script="open -a 'System Preferences';
                                             sketchybar -m --set apple.logo popup.drawing=off"\
              --add item apple.activity popup.apple.logo                                      \
              --set apple.activity icon=􀒓                                                     \
                               label="Activity"                                               \
                               click_script="open -a 'Activity Monitor';
                                             sketchybar -m --set apple.logo popup.drawing=off"\
                                                                                              \
              --add item apple.lock popup.apple.logo                                          \
              --set apple.lock icon=􀒳                                                         \
                               label="Lock Screen"                                            \
                               click_script="pmset displaysleepnow;
                                             sketchybar -m --set apple.logo popup.drawing=off"\
                                                                                              \
              --add item apple.reload_sketchybar popup.apple.logo                             \
              --set apple.reload_sketchybar icon=􀚂                                            \
                               label="Reload sketchybar"                                      \
                               click_script="brew services restart sketchybar"                 \
                                                                                              \
              --add item apple.reload_yabai popup.apple.logo                                  \
              --set apple.reload_yabai icon=􀚂                                                 \
                               label="Reload yabai"                                           \
                               click_script="brew services restart yabai;
                                             sketchybar -m --set apple.logo popup.drawing=off"\
                                                                                              \
              --add item apple.reload_skhd popup.apple.logo                                   \
              --set apple.reload_skhd icon=􀚂                                                  \
                               label="Reload skhd"                                            \
                               click_script="brew services restart skhd
                                             sketchybar -m --set apple.logo popup.drawing=off"
