#!/usr/bin/env bash

sketchybar  --add item clock right        \
            --set clock                   \
                  icon=                  \
                  icon.y_offset=1         \
                  update_freq=10          \
                  script="$PLUGIN_DIR/clock.sh"

