#!/usr/bin/env bash

sketchybar  --add item front_app left                 \
            --set front_app                           \
                  icon.font="$FONT_FACE:Regular:14.0" \
                  background.padding_left=0           \
                  background.padding_right=0          \
                  label.drawing=no                    \
                  script="$PLUGIN_DIR/front_app.sh"   \
                  label="..."                         \
                  label.drawing=yes

sketchybar  --add bracket front_app_bracket  \
                  front_app                  \
            --subscribe front_app front_app_switched
