#!/usr/bin/env bash

sketchybar  --add item now_playing left               \
            --set now_playing                         \
                  icon.font="$FONT_FACE:Regular:14.0" \
                  label.drawing=no                    \
                  script="$PLUGIN_DIR/now_playing.sh" \
                  label="..."                         \
                  label.drawing=yes
