#!/usr/bin/env bash

sketchybar --add item volume right                                  \
           --set volume updates=on                                  \
                        icon.background.drawing=on                  \
                        icon.align=right                            \
                        background.drawing=on                       \
                        align=left                                  \
                        script="$PLUGIN_DIR/volume.sh"              \
                        click_script="$PLUGIN_DIR/volume_click.sh"  \
           --subscribe volume volume_change
