#!/usr/bin/env bash

PLUGIN_DIR="$HOME/.config/sketchybar/plugins"
FONT_FACE="FiraCode Nerd Font"

BUILT_IN_DISPLAY=$(system_profiler SPDisplaysDataType | grep -c 'Built-in Liquid Retina XDR Display')

sketchybar  --bar                 \
                height=32         \
                blur_radius=0     \
                position=top      \
                sticky=on         \
                notch_width=300   \
                padding_left=10   \
                padding_right=10  \
                display=main      \
                color=0x6624273a

sketchybar  --default                                 \
                updates=when_shown                    \
                background.color=0xff24273a           \
                background.padding_left=2             \
                background.padding_right=2            \
                background.corner_radius=5            \
                background.height=24                  \
                icon.color=0xffffffff                 \
                icon.font="$FONT_FACE:Regular:17.0"   \
                icon.padding_left=8                   \
                icon.padding_right=7                  \
                label.font="$FONT_FACE:Regular:12.0"  \
                label.color=0xffcad3f5                \
                label.padding_left=0                  \
                label.padding_right=7

sketchybar --add event lock   "com.apple.screenIsLocked"   \
           --add event unlock "com.apple.screenIsUnlocked" \
                                                           \
           --add item         animator left                \
           --set animator     drawing=off                  \
                              updates=on                   \
                              script="$PLUGIN_DIR/wake.sh" \
           --subscribe        animator lock unlock

# Left
source "$HOME/.config/sketchybar/items/apple_logo"
source "$HOME/.config/sketchybar/items/front_app"

# Center
if [[ $BUILT_IN_DISPLAY -eq "" ]]; then
  source "$HOME/.config/sketchybar/items/now_playing"
fi

# Right
source "$HOME/.config/sketchybar/items/clock"
source "$HOME/.config/sketchybar/items/volume"
source "$HOME/.config/sketchybar/items/battery"

if [[ $BUILT_IN_DISPLAY -eq 1 ]]; then
  source "$HOME/.config/sketchybar/items/now_playing"
fi

sketchybar --update

# Some items need a little help on startup
#
# front_app
sketchybar --trigger front_app_switched INFO="$(yabai -m query --windows --window | jq -r .app)"
#
# volume
sketchybar --trigger volume_change INFO="$(osascript -e 'output volume of (get volume settings)')"
