#!/usr/bin/env bash

# Unload the macOS WindowManager process
launchctl load -F /System/Library/LaunchAgents/com.apple.WindowManager.plist > /dev/null 2>&1 &

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=display_added action="sleep 1 && $HOME/.config/yabai/create_spaces.sh"
yabai -m signal --add event=display_removed action="sleep 1 && $HOME/.config/yabai/create_spaces.sh"
yabai -m signal --add event=display_changed action="sleep 1 && $HOME/.config/yabai/reset_layout.sh"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

$HOME/.config/yabai/create_spaces.sh

yabai -m config external_bar               all:10:0     \
                window_border              off          \
                mouse_follows_focus        off          \
                focus_follows_mouse        on           \
                window_placement           second_child \
                window_topmost             off          \
                window_shadow              float        \
                window_opacity             off          \
                window_opacity_duration    0.15         \
                active_window_opacity      1.0          \
                normal_window_opacity      0.95         \
                window_border_width        1            \
                window_border_hidpi        on           \
                window_border_radius       10           \
                window_animation_duration  0            \
                active_window_border_color 0xffe1e3e4   \
                normal_window_border_color 0xff2a2f38   \
                insert_feedback_color      0xff9dd274   \
                split_ratio                0.50         \
                auto_balance               off          \
                mouse_modifier             fn           \
                mouse_action1              move         \
                mouse_action2              resize       \
                mouse_drop_action          swap         \
                                                        \
                top_padding                 0           \
                bottom_padding             10           \
                left_padding               10           \
                right_padding              10           \
                window_gap                 20

# Exclude problematic apps from being managed:
yabai -m rule --add app="^(Finder|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|App Store|Activity Monitor|MetaClient)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add app="System Information" manage=off
yabai -m rule --add app="Caffeine" manage=off
yabai -m rule --add app="ColorSlurp" manage=off
yabai -m rule --add app="Arc" title="" subrole="AXSystemDialog" manage=off mouse_follows_focus=off

# Specific sizes
yabai -m rule --add label="Telegram" app="^Telegram$" space=2

yabai -m config layout bsp

$HOME/.config/yabai/reset_layout.sh

echo "yabai configuration loaded.."
